### PR TITLE
Building with Backgrounds and Gradients

### PR DESCRIPTION
**Pull request by sundayezeilo**
This project consists of building a webpage using images as a background and adding gradients to elements.
The goal is to make a clone of old an old version of the Apple website webpage.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @ezeilo-su, good work on this project:clap:. Let's consider the following changes:**

1. The page should be without a horizontal scroll. Try to fix this.

2. Use of Semantic HTML - wrap your main navigation links in `<nav>` tags and the dominant content on the page in `<main>` tags. Just like you have used the `<footer>` tag appropriately.

3. Enable stickler for this repository and ensure all lint errors are fixed.

**Suggestions for your README**
 1. I think the screenshot will look better if the taskbar and even the browser tabs are excluded.

 2. You should use hyperlinks to keep urls shorter and neater. You can check the [Microverse Readme template](https://github.com/microverseinc/readme-template) provided here

_**Kindly make these changes and submit another code review request.**_

**Cheers:stars:**

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @ezeilo-su        
#### Great Job so far, but there is one more thing to do . 
### General
- [ ] Enable stickler for this repository and ensure all lint errors are fixed(as stipulated by previous reviewer).

### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @ezeilo-su  ,  You have done a great job with this project. :clap:

**Comment by sundayezeilo** [comment]
I am really happy that my project has passed this process and has gotten approval. Thank you so much for the review.

**Pull request merged**
